### ISSUE TITLE
移动端的一些解决方案

### ISSUE THREAD

**Issue by Justforfei** [Justforfei/F2E_Blog#8]
### 图片/video

行为应该是
- 总是铺满屏幕宽度
- 总是保持宽高比。

四种思路
- 使用before伪元素的margin撑开高度，这种方法是比较干净的纯css实现(推荐)
  问题：
      \* 要求特定html结构
- 一是利用img标签的特性，只设宽度等图片加载完
  问题：
      - 非固定高度会导致懒加载等功能难以实现
      - 导致大量的重排
- 使用其它相对单位，本来最合适的单位是vw，它的含义是视口宽度
  问题：
      \* 存在严重的兼容问题
- 好配合js   用js给html设置一个跟屏幕宽度成正比的font-size，然后把元素宽高都用rem作为单位
  问题：
      \* 某些Android机型会丢掉rem小数部分
      \* 不是纯css方案
      \* 可能会出现页面跳动
### 横竖屏
- js代码控制

window.addEventListener("orientationchange",function () {
        This.isOrietation = true;
        This.changeOriention();
    });
//建议执行横竖屏的事件都通过一个侦听完成，做一个统一的管理；在屏幕横竖屏切换完成之后再执行相应的事件
- css控制

//定义横屏显示的样式
@media screen and(orientation:landspace){...}
//定义竖屏显示的样式
@media screen and(orientation:portrait){...}
//某个尺寸的特殊样式 竖屏时宽度为768px 符合一般ipad的条件
@media only screen and(orientation:portrait) and(device-width:768px){...}
### 背景拉伸
-  选择性的舍弃一些内容？
-  纯色补白？
-  留边界？
### 短屏，窄屏
- 减少的内容如何适配
#### 0.5px
- css的border-width值支持.5px，显示状态受屏幕分辨率的影响
- ios 8和winphone 8的设备对高清屏做了特殊处理，支持显示border-width:.5px
- android 几乎所有的机型不支持显示.5px的边框
#### viewport
- 根据手机的dpr，设置meta标签内， initial-scale的值
- 对页面适配方式有要求
#### background-image
- 需要使用到图片
#### background linear-gradient
- 低端机上大量使用 linear-gradient 会造成卡顿

``` css
background: linear-gradient(transparent 0%, transparent 50%, #b7b6bb 50%, #b7b6bb 100%)

background:
    linear-gradient(180deg, black, black 50%, transparent 50%) top    left  / 100% 1px no-repeat,
    linear-gradient(90deg,  black, black 50%, transparent 50%) top    right / 1px 100% no-repeat,
    linear-gradient(0,      black, black 50%, transparent 50%) bottom right / 100% 1px no-repeat,
    linear-gradient(-90deg, black, black 50%, transparent 50%) bottom left  / 1px 100% no-repeat;

```
#### transform:scale

实现带圆角border

``` css
.btn {position: relative; width: 200px; height: 42px; -webkit-border-radius: 5px; border-radius: 5px; text-align: center; line-height: 42px; background-color: #EDEDED; }
.btn:before {content: ''; position: absolute; top: -50%; bottom: -50%; left: -50%; right: -50%; -webkit-transform: scale(0.5); transform: scale(0.5); border-style: solid; border-width: 1px; border-color: red; -webkit-border-radius: 10px; border-radius: 10px; }
```

**先定义1px的圆角边框，然后拉伸内容的宽度和高度为父级的2倍(边框厚度不变)，然后再使用transform:scale(0.5)缩放为原来的0.5倍**

Tips:
_在魅族 dpr=3 的屏幕上，多条线时，每三条会有一条消失_
- 各种方案测试[9](http://mutian.wang/demo/2015/hairlines/)
- 0.5px
  ios8以上
- box-shadow
- border-image
- 背景渐变
- 伪对象 + transform缩放
  魅族会有问题
## 移动端适配解决方案
- 用px还原设计稿，根据宽度比例进行zoom
                                  根据高度比例进行zoom
- 用px还原设计稿，使用媒体查询进行zoom
- 用px还原设计稿，根据宽度比例进行scale
                                  根据高度比例进行scale
  [62]:https://github.com/peunzhang/pageResponse
  [63]:https://github.com/ufologist/responsive-page/blob/master/responsive-page.js
- 用rem还原设计稿，使用mediaQuery给根元素设置font-size
  
  [61]:http://isux.tencent.com/web-app-rem.html
- 用rem还原设计稿，使用js给根元素设置font-size
  [64]:https://github.com/amfe/lib-flexible/blob/master/src/flexible.js

单页页面：px为单位；定宽，左右多余的留白（用rem适应或者zoom放大）
### PPI适配

一段文字，当你面对不同的屏幕时你希望它的行为是怎样的

行为应该是
- 不希望文字在Retina屏尺寸变小
- 在大屏手机上，希望看到更多文字
### DPR匹配

设计稿上有1像素边框，当你面对不同的屏幕时你希望它的行为是怎样的（1px border）

行为应该是
- 希望在任何屏幕上这条线都是1物理像素

<meta name="viewport" content="initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no">
无法写出1px宽度的东西
### ios，独有的一些属性

-webkit-overflow-scrolling
position: -webkit-sticky
### 字体设置

移动端如何定义字体font-family 
body{font-family:Helvetica;}
### 表单相关

取消input在ios下，输入的时候英文首字母的默认大写
<input autocapitalize="off" autocorrect="off" />

android 上去掉语音输入按钮
input::-webkit-input-speech-button {display: none}

placeholder字体颜色
input::-webkit-input-placeholder{color:#AAAAAA;}
input:focus::-webkit-input-placeholder{color:#EEEEEE;}

Tips:
_关于 ::-webkit- 的伪类，具体可以打开浏览器的shadow dom 就可以看到有哪些元素特有的可定制伪类_
#### 微信

``` javascript
wx.ready(function() {
    document.getElementById('bgmusic').play();
});

document.addEventListener('touchstart', function () {
    document.getElementsByTagName('audio')[0].play();
});
```
